apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: p8-kyverno-policies
  namespace: argocd
  annotations:
    # Ola 1: las politicas requieren los CRDs de Kyverno (ola 0)
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/BillyDread1531/Practicas-SA-B-201901385.git
    targetRevision: main
    path: P8/security/kyverno
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
